"""Behavior Detection Service - lightweight heuristic suspicious behavior detection."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional
from dataclasses import dataclass, field

from forensics_sandbox_agent.app.config.monitoring_models import BehaviorDetectionConfig
from forensics_sandbox_agent.infrastructure.monitoring.event_pipeline import ForensicEventPipeline
from forensics_sandbox_agent.infrastructure.monitoring.event_models import (
    SuspiciousIndicator,
    EventSeverity,
)


@dataclass
class BehaviorAlert:
    """Alert generated by behavior detection."""
    indicator: SuspiciousIndicator
    severity: EventSeverity
    description: str
    timestamp: datetime
    evidence: list[str] = field(default_factory=list)


class BehaviorDetector:
    """Detects suspicious behaviors using lightweight heuristics."""

    def __init__(
        self,
        config: BehaviorDetectionConfig,
        pipeline: ForensicEventPipeline,
        logger: logging.Logger,
    ) -> None:
        self._config = config
        self._pipeline = pipeline
        self._logger = logger
        self._alerts: list[BehaviorAlert] = []
        self._is_active = False

        self._file_operation_count = 0
        self._process_spawn_count = 0
        self._registry_operation_count = 0
        self._network_connection_count = 0

    def start(self) -> None:
        """Start behavior detection."""
        self._is_active = True
        self._alerts.clear()
        self._reset_counters()
        self._logger.info("Behavior detection started")

    def stop(self) -> None:
        """Stop behavior detection."""
        self._is_active = False
        self._logger.info(f"Behavior detection stopped - generated {len(self._alerts)} alerts")

    def _reset_counters(self) -> None:
        """Reset operation counters."""
        self._file_operation_count = 0
        self._process_spawn_count = 0
        self._registry_operation_count = 0
        self._network_connection_count = 0

    def on_file_operation(self, file_path: str, operation: str) -> None:
        """Analyze file operation for suspicious behavior."""
        if not self._is_active or not self._config.detect_mass_file_mods:
            return

        self._file_operation_count += 1

        now = datetime.now()
        threshold = 100

        if self._file_operation_count > threshold:
            alert = BehaviorAlert(
                indicator=SuspiciousIndicator.MASS_FILE_ACTIVITY,
                severity=EventSeverity.MEDIUM,
                description=f"Mass file activity detected ({self._file_operation_count} operations)",
                timestamp=now,
                evidence=[
                    f"Total file operations: {self._file_operation_count}",
                    f"Recent operation: {operation} - {file_path}",
                ],
            )
            self._alerts.append(alert)
            self._emit_alert_event(alert)
            self._file_operation_count = 0

        suspicious_paths = ["temp", "appdata", "startup", "system32", "windows"]
        path_lower = file_path.lower()
        if any(s in path_lower for s in suspicious_paths):
            suspicious_ext = [".exe", ".dll", ".bat", ".ps1", ".vbs", ".cmd"]
            if any(file_path.lower().endswith(ext) for ext in suspicious_ext):
                alert = BehaviorAlert(
                    indicator=SuspiciousIndicator.SUSPICIOUS_PATH,
                    severity=EventSeverity.LOW,
                    description=f"Suspicious executable path detected",
                    timestamp=now,
                    evidence=[
                        f"Path: {file_path}",
                        f"Operation: {operation}",
                    ],
                )
                self._alerts.append(alert)

    def on_process_spawn(self, executable_path: str, parent_path: Optional[str] = None) -> None:
        """Analyze process spawn for suspicious behavior."""
        if not self._is_active or not self._config.detect_rapid_process_spawn:
            return

        self._process_spawn_count += 1

        if self._process_spawn_count > 20:
            alert = BehaviorAlert(
                indicator=SuspiciousIndicator.RAPID_PROCESS_SPAWN,
                severity=EventSeverity.MEDIUM,
                description=f"Rapid process spawning detected ({self._process_spawn_count} processes)",
                timestamp=datetime.now(),
                evidence=[
                    f"Total processes: {self._process_spawn_count}",
                    f"Latest: {executable_path}",
                ],
            )
            self._alerts.append(alert)
            self._emit_alert_event(alert)
            self._process_spawn_count = 0

        suspicious_executables = ["cmd.exe", "powershell.exe", "wscript.exe", "cscript.exe"]
        if any(exe.lower() in executable_path.lower() for exe in suspicious_executables):
            alert = BehaviorAlert(
                indicator=SuspiciousIndicator.UNUSUAL_EXECUTION,
                severity=EventSeverity.LOW,
                description=f"Suspicious command interpreter execution",
                timestamp=datetime.now(),
                evidence=[
                    f"Executable: {executable_path}",
                    f"Parent: {parent_path or 'unknown'}",
                ],
            )
            self._alerts.append(alert)

    def on_registry_operation(self, key_path: str, operation: str) -> None:
        """Analyze registry operation for suspicious behavior."""
        if not self._is_active or not self._config.detect_suspicious_registry:
            return

        self._registry_operation_count += 1

        autorun_paths = ["run", "runonce", "winlogon", "shell"]
        path_lower = key_path.lower()

        if any(autorun in path_lower for autorun in autorun_paths):
            alert = BehaviorAlert(
                indicator=SuspiciousIndicator.PERSISTENCE_ATTEMPT,
                severity=EventSeverity.HIGH,
                description=f"Autorun registry modification detected",
                timestamp=datetime.now(),
                evidence=[
                    f"Key path: {key_path}",
                    f"Operation: {operation}",
                ],
            )
            self._alerts.append(alert)
            self._emit_alert_event(alert)

    def on_network_connection(
        self,
        destination_ip: str,
        port: Optional[int],
        protocol: str,
    ) -> None:
        """Analyze network connection for suspicious behavior."""
        if not self._is_active or not self._config.detect_unusual_network:
            return

        self._network_connection_count += 1

        suspicious_ports = [4444, 5555, 6666, 31337, 8080, 9001]
        if port in suspicious_ports:
            alert = BehaviorAlert(
                indicator=SuspiciousIndicator.SUSPICIOUS_NETWORK,
                severity=EventSeverity.MEDIUM,
                description=f"Connection to suspicious port detected",
                timestamp=datetime.now(),
                evidence=[
                    f"Destination: {destination_ip}",
                    f"Port: {port}",
                    f"Protocol: {protocol}",
                ],
            )
            self._alerts.append(alert)
            self._emit_alert_event(alert)

        if self._network_connection_count > 50:
            alert = BehaviorAlert(
                indicator=SuspiciousIndicator.SUSPICIOUS_NETWORK,
                severity=EventSeverity.LOW,
                description=f"High volume of network connections",
                timestamp=datetime.now(),
                evidence=[
                    f"Total connections: {self._network_connection_count}",
                ],
            )
            self._alerts.append(alert)
            self._network_connection_count = 0

    def _emit_alert_event(self, alert: BehaviorAlert) -> None:
        """Emit a forensic event for the behavior alert."""
        from forensics_sandbox_agent.infrastructure.monitoring.event_models import (
            EventCategory,
            EventOperation,
        )

        self._pipeline.emit_event(
            category=EventCategory.BEHAVIOR,
            operation=EventOperation.PROCESS_CREATE,
            severity=alert.severity,
            source="behavior_detector",
            details={
                "indicator": alert.indicator.value,
                "description": alert.description,
                "evidence": alert.evidence,
            },
            suspicious_indicators=[alert.indicator],
        )

        self._logger.warning(f"Behavior alert: {alert.description}")

    def get_alerts(self) -> list[BehaviorAlert]:
        """Get all behavior alerts."""
        return self._alerts.copy()

    def get_alerts_by_severity(self, severity: EventSeverity) -> list[BehaviorAlert]:
        """Get alerts filtered by severity."""
        return [a for a in self._alerts if a.severity == severity]

    def get_alert_summary(self) -> dict:
        """Get summary of behavior alerts."""
        severity_counts = {}
        for alert in self._alerts:
            severity = alert.severity.value
            severity_counts[severity] = severity_counts.get(severity, 0) + 1

        return {
            "total_alerts": len(self._alerts),
            "alerts_by_severity": severity_counts,
            "indicators": list(set(a.indicator.value for a in self._alerts)),
        }

    def clear_alerts(self) -> None:
        """Clear all behavior alerts."""
        self._alerts.clear()
        self._reset_counters()